apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-web
  template:
    metadata:
      labels:
        app: matrix-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
