# yamllint disable
# Q8: Broken Deployment YAML with intentional errors
# 1. Uses deprecated API version (extensions/v1beta1)
# 2. Missing required selector field
# 3. Template labels don't match (if selector was present)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broken-app
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
