# Q9 - Canary Deployment Template
# Task: Create a canary deployment alongside stable-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v2
  namespace: blaze
  labels:
    app: web-frontend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
      version: v2
  template:
    metadata:
      labels:
        app: web-frontend
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
