# Template: Deployment with InitContainer to add
# Copy this to ./exam/course/14/init-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-app
  namespace: orion
  labels:
    app: init-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-app
  template:
    metadata:
      labels:
        app: init-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data-volume
        emptyDir: {}
      # TODO: Add initContainer here
