# CKAD Simulation 2 - Namespaces
# Greek mythology themed namespaces for Dojo Byakko 🐯
---
apiVersion: v1
kind: Namespace
metadata:
  name: olympus
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: zeus
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: athena
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: artemis
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: hermes
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: poseidon
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: hades
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: hera
  labels:
    exam: ckad-simulation2
    theme: greek
---
apiVersion: v1
kind: Namespace
metadata:
  name: ares
  labels:
    exam: ckad-simulation2
    theme: greek
