apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genesis-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "genesis-web.name" . }}
    helm.sh/chart: {{ include "genesis-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    custom-label: {{ .Values.customLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "genesis-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "genesis-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        custom-label: {{ .Values.customLabel }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
